openapi: 3.0.0
info:
  title: Minka Ledger API - Connect
  version: 2.14.0
  description: |
    Esta especificación cubre paths y componentes necesarios
    para conectar un sistema de pagos utilizando el protocolo Minka.
  termsOfService: http://minka.io/terms/
  contact:
    name: Minka API - Connect
    email: api@minka.io
    url: http://docs.minka.io
  license:
    name: Mozilla Public License 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
servers:
  - url: https://ldg-dev.one/api/v2
    description: Development server
  - url: https://ldg-stg.one/api/v2
    description: Staging server
paths:
  /intents:
    # TODO: Add active ledger parameter to simplify call
    post:
      summary: Crear un intento (intent)
      operationId: createIntent
      tags:
        - Intent
      requestBody:
        description: Intent body
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateIntentRequest"
      responses:
        "201":
          description: Created Intent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateIntentResponse"
      description: Intento de pago
  /intents/{id}/proofs:
    post:
      summary: Agregar prueba a un intento de pago
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: identificador del intento de pago
      tags:
        - IntentProof
      requestBody:
        description: Firma para agregar prueba al intent.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateIntentRequest"
      responses:
        "201":
          description: signed Intent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateIntentResponse"
components:
  schemas:
    CreateIntentRequest:
      type: object
      properties:
        hash:
          type: string
          description: El hash único del intento.
        data:
          $ref: "#/components/schemas/IntentData"
        meta:
          type: object
          properties:
            proofs:
              type: array
              items:
                $ref: "#/components/schemas/proof"
            routed:
              type: boolean
              description: Indica si el intento fue enrutado.
              example: true
            status:
              type: string
              description: El estado del intento.
              example: "completed"
            thread:
              type: string
              description: El identificador del hilo.
              example: "7RFbLLoTabUa7zX1W"
            moment:
              type: string
              format: date-time
              description: La marca de tiempo del evento meta.
              example: "2024-08-30T03:34:19.938Z"
            owners:
              type: array
              items:
                type: string
                description: Las claves públicas de los propietarios.
                example: "rpteZ4kOuiB6a9/KHCqOc8HcW5J20Hrb5D4ZCbZYpSE="
    CreateIntentResponse:
      type: object
      properties:
        hash:
          type: string
          description: El hash único del intento.
        data:
          $ref: "#/components/schemas/IntentData"
        meta:
          type: object
          properties:
            proofs:
              type: array
              items:
                $ref: "#/components/schemas/proof"
            routed:
              type: boolean
              description: Indica si el intento fue enrutado.
              example: true
            status:
              type: string
              description: El estado del intento.
              example: "completed"
            thread:
              type: string
              description: El identificador del hilo.
              example: "7RFbLLoTabUa7zX1W"
            moment:
              type: string
              format: date-time
              description: La marca de tiempo del evento meta.
              example: "2024-08-30T03:34:19.938Z"
            owners:
              type: array
              items:
                type: string
                description: Las claves públicas de los propietarios.
                example: "rpteZ4kOuiB6a9/KHCqOc8HcW5J20Hrb5D4ZCbZYpSE="
  
    IntentData:
      type: object
      properties:
        handle:
          type: string
          description: El identificador del request. Este campo garantiza la idempotencia del request. Se sugiere usar GUID
          example: k3PdrLoh1m1BnKlr0Kou7
        claims:
          type: array
          items:
            $ref: "#/components/schemas/Claim"
        schema:
          type: string
          description: Referencia a esquema de del intento.
          example: transfer
        access:
          type: array
          items:
            $ref: "#/components/schemas/Access"
    Access:
      type: object
      properties:
        action:
          type: string
          description: El tipo de acción de acceso.
          example: "any"
        signer:
          type: object
          properties:
            public:
              type: string
              description: La clave pública del firmante.
              example: "rpteZ4kOuiB6a9/KHCqOc8HcW5J20Hrb5D4ZCbZYpSE="
        bearer:
          type: object
          properties:
            $signer:
              type: object
              properties:
                public:
                  type: string
                  description: La clave pública del portador.
                  example: "rpteZ4kOuiB6a9/KHCqOc8HcW5J20Hrb5D4ZCbZYpSE="
    Claim:
      type: object
      properties:
        action:
          type: string
          description: Una transacion parte de inento de pago.
          example: "transfer"
        amount:
          type: number
          description: El monto asociado con la transaccion.
          example: 4200
        source:
          $ref: "#/components/schemas/Source"
        symbol:
          $ref: "#/components/schemas/Symbol"
        target:
          $ref: "#/components/schemas/Target"
        custom:
          $ref: "#/components/schemas/claimCustom"
    claimCustom:
      type: object
      properties:
        description:
          type: string
          description: Descripción personalizada de la transacción.
          example: "Primer intento de pago"
    Source:
      type: object
      properties:
        custom:
          $ref: "#/components/schemas/SourceCustom"
        handle:
          type: string
          description: El identificador del participante fuente.
          example: "caho:1001001345@teslabank.io"
    # TODO: Source custom should have OneOf options
    SourceCustom:
      type: object
      properties:
        type:
          type: string
          description: El tipo de entidad del participante fuente.
          example: "Natural" # Add types of person - legal, natural based on ISO
        name:
          type: string
          description: El nombre del participante fuente.
          example: Nikola Tesla
        identificationType:
          type: string
          description: El tipo de identificación del participante fuente
          example: "cc"
        identification:
          type: string
          description: El número de identificación del participante fuente.
          example: "429493434"
        mobileNumber:
          type: string
          description: Telefono de contacto, con el código del país
          example: "+385914242424"
        emailAddress:
          type: string
          description: El punto de anclaje, como un método de contacto, del participante fuente.
          example: nikola@tesla.hr
    Target:
      type: object
      properties:
        custom:
          $ref: "#/components/schemas/TargetCustom"
        handle:
          type: string
          description: El identificador del participante objetivo.
          example: "caho:1001009422@mintbank.dev"
    TargetCustom:
      type: object
      properties:
        type:
          type: string
          description: El tipo de entidad del participante fuente.
          example: "Natural" # Add types of person - legal, natural based on ISO
        name:
          type: string
          description: El nombre del participante fuente.
          example: "Simon Bolivar"
        identificationType:
          type: string
          description: El tipo de identificación del participante fuente.
          # TODO: Add validations based on ISO
          example: "cc"
        identification:
          type: string
          description: El número de identificación del participante fuente.
          example: "429493434"
        mobileNumber:
          type: string
          description: Contacto de la persona - telefono.
          example: "+573504242424"
        emailAddress:
          type: string
          description: Contacto de la persona - email.
          example: "simon@gmail.com"
        anchor:
          type: string
          description: Llave usada para resolver el destino (target anchor).
          example: tel:+57350424242
    # We should add examples OneOf
    Symbol:
      type: object
      properties:
        handle:
          type: string
          description: El identificador del símbolo de la moneda.
          example: "cop"
    proof:
      type: object
      properties:
        custom:
          $ref: "#/components/schemas/proofCustom"
        digest:
          type: string
          description: El digest criptográfico de la prueba.
          example: "ccec86775d8b305c5bebeb228a4d6a86578bca526eea9ff11bb563359801c9d1"
        method:
          type: string
          description: El método criptográfico utilizado.
          example: "ed25519-v2"
        public:
          type: string
          description: La clave pública utilizada en la prueba.
          example: "rpteZ4kOuiB6a9/KHCqOc8HcW5J20Hrb5D4ZCbZYpSE="
        result:
          type: string
          description: El resultado del proceso de la prueba.
          example: "1iuU0QxYh/FamG2F5c4qrk3+4nbMOz7MeIRzDiO4FZG2syIE4F1Xu7KgVk0qkwk9RENkXlOr468T34FgbHR7Bg=="
    proofCustom:
      type: object
      properties:
        moment:
          type: string
          format: date-time
          description: La marca de tiempo de la prueba.
          example: "2024-08-30T03:34:19.425Z"
        status:
          type: string
          description: El estado de la prueba.
          example: "initiated"
        detail:
          type: string
          description: Nombre de la marca de tiempo 
          example: "T110"
        deviceName:
          type: string
          description: Nombre del dispositivo
          example: d7bb29de680d2b0c37f2c03215565307c60fbf7a8d15f253fa74d9d5f60fe632
        deviceHash:
          type: string
          description: Hash del dispositivo
          example: d7bb29de680d2b0c37f2c03215565307c60fbf7a8d15f253fa74d9d5f60fe632
        deviceIp:
          type: string
          description: Dirrecion IP de dispositivo originador de Intento de pago
          example: 192.12.12.12
        deviceType:
          type: string
          description: Tipo de dispositivo (Mobile, Web, SecureChannel, AccessToken, ..)
          example: Mobile
      
   
   